sudo: required

notifications:
  email:
    on_success: never
    on_failure: change

cache:
  directories:
    - node_modules
    - vendor
    - $HOME/phpunit-bin

language:
  - php
  - node_js

php:
  - 7.1.3

env:
    global:
        - WP_VERSION=4.8.2
        - WP_MULTISITE=0

install:
  - sudo apt-get install -y libxml2-utils
  - nvm install 6 && nvm use 6
  - npm install && composer install --no-interaction
  - export DEV_LIB_PATH=dev-lib
  - if [ ! -e "$DEV_LIB_PATH" ] && [ -L .travis.yml ]; then export DEV_LIB_PATH=$( dirname $( readlink .travis.yml ) ); fi
  - if [ ! -e "$DEV_LIB_PATH" ]; then git clone https://github.com/xwp/wp-dev-lib.git $DEV_LIB_PATH; fi
  - source $DEV_LIB_PATH/travis.install.sh

script:
  - source $DEV_LIB_PATH/travis.script.sh

after_script:
  - source $DEV_LIB_PATH/travis.after_script.sh
